-- ============================================
-- Seed Data: Movies
-- ============================================

INSERT INTO movies (id, title, description, duration_minutes, language, genre, release_date, rating, imdb_rating, poster_url, trailer_url, cast_info, crew_info) VALUES
(uuid_generate_v4(), 'Pushpa 2: The Rule', 'Pushpa Raj returns with more power, facing new enemies and fighting to rule the smuggling world.', 180, 'Telugu', 'Action, Drama', '2025-12-05', 'UA', 7.8, '/images/movies/pushpa2.jpg', 'https://youtube.com/watch?v=pushpa2', '[{"name":"Allu Arjun","role":"Pushpa Raj"},{"name":"Rashmika Mandanna","role":"Srivalli"},{"name":"Fahadh Faasil","role":"SP Bhanwar Singh Shekhawat"}]', '[{"name":"Sukumar","role":"Director"},{"name":"Mythri Movie Makers","role":"Producer"}]'),

(uuid_generate_v4(), 'Singham Again', 'Bajirao Singham returns with an ensemble cast to fight corruption in an action-packed sequel.', 165, 'Hindi', 'Action, Thriller', '2025-11-01', 'UA', 7.2, '/images/movies/singham-again.jpg', 'https://youtube.com/watch?v=singham', '[{"name":"Ajay Devgn","role":"Singham"},{"name":"Deepika Padukone","role":"Avni"},{"name":"Ranveer Singh","role":"Simmba"}]', '[{"name":"Rohit Shetty","role":"Director"}]'),

(uuid_generate_v4(), 'Stree 3', 'The hilarious horror franchise continues as the gang faces a new paranormal threat.', 150, 'Hindi', 'Horror, Comedy', '2026-08-15', 'UA', 7.5, '/images/movies/stree3.jpg', 'https://youtube.com/watch?v=stree3', '[{"name":"Rajkummar Rao","role":"Vicky"},{"name":"Shraddha Kapoor","role":"Stree"},{"name":"Pankaj Tripathi","role":"Rudra"}]', '[{"name":"Amar Kaushik","role":"Director"}]'),

(uuid_generate_v4(), 'War 2', 'Kabir returns in this high-octane action thriller with breathtaking stunts across the globe.', 155, 'Hindi', 'Action, Thriller', '2026-01-14', 'UA', 7.0, '/images/movies/war2.jpg', 'https://youtube.com/watch?v=war2', '[{"name":"Hrithik Roshan","role":"Kabir"},{"name":"Kiara Advani","role":"Naina"}]', '[{"name":"Ayan Mukerji","role":"Director"},{"name":"Yash Raj Films","role":"Producer"}]'),

(uuid_generate_v4(), 'Dhoom 4', 'The iconic heist franchise returns with a new thief and grander set pieces.', 160, 'Hindi', 'Action, Thriller', '2026-12-25', 'UA', 6.8, '/images/movies/dhoom4.jpg', 'https://youtube.com/watch?v=dhoom4', '[{"name":"Ranbir Kapoor","role":"The Thief"},{"name":"Abhishek Bachchan","role":"ACP Jai Dixit"}]', '[{"name":"Yash Raj Films","role":"Producer"}]'),

(uuid_generate_v4(), 'KGF Chapter 3', 'Rocky Bhai''s empire expands as new challenges arise from powerful adversaries.', 185, 'Kannada', 'Action, Drama', '2026-04-14', 'UA', 8.2, '/images/movies/kgf3.jpg', 'https://youtube.com/watch?v=kgf3', '[{"name":"Yash","role":"Rocky"},{"name":"Sanjay Dutt","role":"Adheera"}]', '[{"name":"Prashanth Neel","role":"Director"},{"name":"Hombale Films","role":"Producer"}]'),

(uuid_generate_v4(), 'RRR 2', 'The dynamic duo returns in another spectacular visual extravaganza set in pre-independence India.', 190, 'Telugu', 'Action, Drama, Musical', '2026-03-25', 'UA', 8.5, '/images/movies/rrr2.jpg', 'https://youtube.com/watch?v=rrr2', '[{"name":"Ram Charan","role":"Alluri Sitarama Raju"},{"name":"Jr NTR","role":"Komaram Bheem"}]', '[{"name":"S. S. Rajamouli","role":"Director"}]'),

(uuid_generate_v4(), 'Brahmastra Part 2: Dev', 'The epic mythological saga continues as Shiva discovers more about his powers.', 170, 'Hindi', 'Fantasy, Action', '2026-09-09', 'UA', 7.3, '/images/movies/brahmastra2.jpg', 'https://youtube.com/watch?v=brahmastra2', '[{"name":"Ranbir Kapoor","role":"Shiva"},{"name":"Alia Bhatt","role":"Isha"},{"name":"Ranveer Singh","role":"Dev"}]', '[{"name":"Ayan Mukerji","role":"Director"},{"name":"Dharma Productions","role":"Producer"}]'),

(uuid_generate_v4(), 'Fighter 2', 'Indian Air Force officers take on an even bigger threat to national security.', 145, 'Hindi', 'Action, Drama', '2026-01-26', 'UA', 7.1, '/images/movies/fighter2.jpg', 'https://youtube.com/watch?v=fighter2', '[{"name":"Hrithik Roshan","role":"Shamsher Pathania"},{"name":"Deepika Padukone","role":"Minal"}]', '[{"name":"Siddharth Anand","role":"Director"}]'),

(uuid_generate_v4(), 'Animal Park', 'A sequel exploring dark family dynamics and the beast within.', 175, 'Hindi', 'Action, Drama, Thriller', '2026-06-06', 'A', 7.6, '/images/movies/animal-park.jpg', 'https://youtube.com/watch?v=animalpark', '[{"name":"Ranbir Kapoor","role":"Ranvijay"},{"name":"Bobby Deol","role":"Abrar"}]', '[{"name":"Sandeep Reddy Vanga","role":"Director"},{"name":"T-Series","role":"Producer"}]'),

(uuid_generate_v4(), 'Jawan 2', 'A vigilante returns with a new mission to protect the common people.', 155, 'Hindi', 'Action, Thriller', '2026-11-11', 'UA', 7.9, '/images/movies/jawan2.jpg', 'https://youtube.com/watch?v=jawan2', '[{"name":"Shah Rukh Khan","role":"Vikram"},{"name":"Nayanthara","role":"Narmada"}]', '[{"name":"Atlee","role":"Director"},{"name":"Red Chillies Entertainment","role":"Producer"}]'),

(uuid_generate_v4(), 'Pathaan 2', 'India''s top spy embarks on his most dangerous mission yet.', 160, 'Hindi', 'Action, Spy, Thriller', '2026-01-25', 'UA', 7.4, '/images/movies/pathaan2.jpg', 'https://youtube.com/watch?v=pathaan2', '[{"name":"Shah Rukh Khan","role":"Pathaan"},{"name":"John Abraham","role":"Jim"}]', '[{"name":"Siddharth Anand","role":"Director"},{"name":"Yash Raj Films","role":"Producer"}]'),

(uuid_generate_v4(), 'Dune: Part Three', 'The epic conclusion of Frank Herbert''s legendary sci-fi saga on the big screen.', 175, 'English', 'Sci-Fi, Adventure, Drama', '2026-11-20', 'UA', 8.7, '/images/movies/dune3.jpg', 'https://youtube.com/watch?v=dune3', '[{"name":"Timothée Chalamet","role":"Paul Atreides"},{"name":"Zendaya","role":"Chani"},{"name":"Florence Pugh","role":"Princess Irulan"}]', '[{"name":"Denis Villeneuve","role":"Director"},{"name":"Legendary Pictures","role":"Producer"}]'),

(uuid_generate_v4(), 'Avatar 3: Fire and Ash', 'The Na''vi face a new threat as a volcanic civilization rises on Pandora.', 200, 'English', 'Sci-Fi, Adventure, Fantasy', '2025-12-19', 'UA', 8.0, '/images/movies/avatar3.jpg', 'https://youtube.com/watch?v=avatar3', '[{"name":"Sam Worthington","role":"Jake Sully"},{"name":"Zoe Saldaña","role":"Neytiri"}]', '[{"name":"James Cameron","role":"Director"},{"name":"20th Century Studios","role":"Producer"}]'),

(uuid_generate_v4(), 'The Batman 2', 'The Dark Knight faces a new villain threatening to tear Gotham apart.', 165, 'English', 'Action, Crime, Drama', '2026-10-02', 'UA', 8.3, '/images/movies/batman2.jpg', 'https://youtube.com/watch?v=batman2', '[{"name":"Robert Pattinson","role":"Bruce Wayne / Batman"},{"name":"Zoë Kravitz","role":"Selina Kyle"}]', '[{"name":"Matt Reeves","role":"Director"},{"name":"Warner Bros.","role":"Producer"}]'),

(uuid_generate_v4(), 'Avengers: Secret Wars', 'The multiverse collides in the ultimate Marvel crossover event.', 180, 'English', 'Action, Sci-Fi, Adventure', '2026-05-01', 'UA', 8.8, '/images/movies/secret-wars.jpg', 'https://youtube.com/watch?v=secretwars', '[{"name":"Robert Downey Jr.","role":"Doctor Doom"},{"name":"Pedro Pascal","role":"Reed Richards"}]', '[{"name":"Russo Brothers","role":"Directors"},{"name":"Marvel Studios","role":"Producer"}]'),

(uuid_generate_v4(), 'Vikram 2', 'The elite squad faces an international conspiracy that threatens India.', 160, 'Tamil', 'Action, Thriller', '2026-06-14', 'UA', 7.7, '/images/movies/vikram2.jpg', 'https://youtube.com/watch?v=vikram2', '[{"name":"Kamal Haasan","role":"Vikram"},{"name":"Vijay Sethupathi","role":"Santhanam"},{"name":"Fahadh Faasil","role":"Amar"}]', '[{"name":"Lokesh Kanagaraj","role":"Director"}]'),

(uuid_generate_v4(), 'Ponniyin Selvan 3', 'The epic Chola dynasty saga continues with political intrigue and war.', 175, 'Tamil', 'Historical, Drama', '2026-04-28', 'U', 7.9, '/images/movies/ps3.jpg', 'https://youtube.com/watch?v=ps3', '[{"name":"Vikram","role":"Aditya Karikalan"},{"name":"Aishwarya Rai","role":"Nandini"},{"name":"Jayam Ravi","role":"Arulmozhi Varman"}]', '[{"name":"Mani Ratnam","role":"Director"}]'),

(uuid_generate_v4(), 'Salaar: Part 2 - Shouryanga Parvam', 'The violent saga of power continues as Deva faces betrayal.', 170, 'Telugu', 'Action, Thriller', '2026-03-28', 'UA', 7.5, '/images/movies/salaar2.jpg', 'https://youtube.com/watch?v=salaar2', '[{"name":"Prabhas","role":"Deva"},{"name":"Prithviraj Sukumaran","role":"Vardharaja Mannar"}]', '[{"name":"Prashanth Neel","role":"Director"},{"name":"Hombale Films","role":"Producer"}]'),

(uuid_generate_v4(), 'Kantara: Chapter 1', 'The prequel exploring the divine origins of the Kantara mythology.', 165, 'Kannada', 'Action, Fantasy, Thriller', '2025-10-02', 'UA', 8.1, '/images/movies/kantara2.jpg', 'https://youtube.com/watch?v=kantara2', '[{"name":"Rishab Shetty","role":"Lead"},{"name":"Sapthami Gowda","role":"Lead"}]', '[{"name":"Rishab Shetty","role":"Director"},{"name":"Hombale Films","role":"Producer"}]'),

(uuid_generate_v4(), 'Inception 2', 'Dom Cobb is pulled back into the world of dream heists for an impossible task.', 160, 'English', 'Sci-Fi, Action, Thriller', '2026-07-17', 'UA', 9.0, '/images/movies/inception2.jpg', 'https://youtube.com/watch?v=inception2', '[{"name":"Leonardo DiCaprio","role":"Dom Cobb"},{"name":"Tom Hardy","role":"Eames"}]', '[{"name":"Christopher Nolan","role":"Director"},{"name":"Warner Bros.","role":"Producer"}]'),

(uuid_generate_v4(), 'Dangal 2', 'The Phogat wrestling legacy continues with the next generation.', 155, 'Hindi', 'Sports, Drama', '2026-08-15', 'U', 8.0, '/images/movies/dangal2.jpg', 'https://youtube.com/watch?v=dangal2', '[{"name":"Aamir Khan","role":"Mahavir Singh Phogat"},{"name":"Fatima Sana Shaikh","role":"Geeta Phogat"}]', '[{"name":"Nitesh Tiwari","role":"Director"}]'),

(uuid_generate_v4(), 'Laapataa Ladies 2', 'A heartwarming sequel exploring small-town India with humor and heart.', 130, 'Hindi', 'Comedy, Drama', '2026-02-14', 'U', 7.8, '/images/movies/laapataa2.jpg', 'https://youtube.com/watch?v=laapataa2', '[{"name":"Nitanshi Goel","role":"Phool"},{"name":"Pratibha Ranta","role":"Jaya"}]', '[{"name":"Kiran Rao","role":"Director"},{"name":"Aamir Khan Productions","role":"Producer"}]'),

(uuid_generate_v4(), 'Spider-Man: Beyond the Spider-Verse', 'Miles Morales faces his ultimate challenge across infinite dimensions.', 150, 'English', 'Animation, Action, Adventure', '2026-03-28', 'UA', 9.1, '/images/movies/spiderverse3.jpg', 'https://youtube.com/watch?v=spiderverse3', '[{"name":"Shameik Moore","role":"Miles Morales (voice)"},{"name":"Hailee Steinfeld","role":"Gwen Stacy (voice)"}]', '[{"name":"Sony Pictures Animation","role":"Studio"}]'),

(uuid_generate_v4(), 'Interstellar 2', 'A new crew ventures through a wormhole to save humanity from extinction.', 180, 'English', 'Sci-Fi, Drama', '2026-11-07', 'UA', 9.2, '/images/movies/interstellar2.jpg', 'https://youtube.com/watch?v=interstellar2', '[{"name":"Matthew McConaughey","role":"Cooper"},{"name":"Anne Hathaway","role":"Dr. Brand"}]', '[{"name":"Christopher Nolan","role":"Director"},{"name":"Paramount Pictures","role":"Producer"}]'),

(uuid_generate_v4(), 'Bhool Bhulaiyaa 3', 'Rooh Baba faces his scariest challenge yet in a haunted palace.', 145, 'Hindi', 'Horror, Comedy', '2026-10-31', 'UA', 7.2, '/images/movies/bhool3.jpg', 'https://youtube.com/watch?v=bhool3', '[{"name":"Kartik Aaryan","role":"Rooh Baba"},{"name":"Vidya Balan","role":"Manjulika"},{"name":"Madhuri Dixit","role":"Queen"}]', '[{"name":"Anees Bazmee","role":"Director"},{"name":"T-Series","role":"Producer"}]'),

(uuid_generate_v4(), 'Kalki 2899 AD: Part 2', 'The epic mythological sci-fi saga reaches its climax in a dystopian future.', 180, 'Telugu', 'Sci-Fi, Action, Mythology', '2026-05-09', 'UA', 8.0, '/images/movies/kalki2.jpg', 'https://youtube.com/watch?v=kalki2', '[{"name":"Prabhas","role":"Bhairava"},{"name":"Deepika Padukone","role":"SUM-80"},{"name":"Amitabh Bachchan","role":"Ashwatthama"}]', '[{"name":"Nag Ashwin","role":"Director"},{"name":"Vyjayanthi Movies","role":"Producer"}]'),

(uuid_generate_v4(), 'Mission Impossible: The Final Reckoning Part 2', 'Ethan Hunt''s final mission to save the world from an AI threat.', 165, 'English', 'Action, Spy, Thriller', '2026-05-23', 'UA', 8.4, '/images/movies/mi8.jpg', 'https://youtube.com/watch?v=mi8', '[{"name":"Tom Cruise","role":"Ethan Hunt"},{"name":"Hayley Atwell","role":"Grace"}]', '[{"name":"Christopher McQuarrie","role":"Director"},{"name":"Paramount Pictures","role":"Producer"}]'),

(uuid_generate_v4(), 'Gadar 3', 'Tara Singh returns for one final fight for his family and nation.', 160, 'Hindi', 'Action, Drama', '2026-08-15', 'UA', 7.0, '/images/movies/gadar3.jpg', 'https://youtube.com/watch?v=gadar3', '[{"name":"Sunny Deol","role":"Tara Singh"},{"name":"Ameesha Patel","role":"Sakina"}]', '[{"name":"Anil Sharma","role":"Director"}]'),

(uuid_generate_v4(), 'Joker: Folie à Trois', 'The third chapter of the Joker''s descent explores the consequences of chaos.', 145, 'English', 'Crime, Drama, Thriller', '2026-10-03', 'A', 8.1, '/images/movies/joker3.jpg', 'https://youtube.com/watch?v=joker3', '[{"name":"Joaquin Phoenix","role":"Arthur Fleck / Joker"},{"name":"Lady Gaga","role":"Harley Quinn"}]', '[{"name":"Todd Phillips","role":"Director"},{"name":"Warner Bros.","role":"Producer"}]');
