apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: bookmyshow
type: Opaque
stringData:
  DB_USERNAME: "bookmyshow_user"
  DB_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  JWT_SECRET: "CHANGE_ME_BASE64_ENCODED_SECRET_KEY_AT_LEAST_256_BITS"
  REDIS_PASSWORD: ""
  RAZORPAY_KEY_ID: ""
  RAZORPAY_KEY_SECRET: ""
  STRIPE_SECRET_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  TWILIO_ACCOUNT_SID: ""
  TWILIO_AUTH_TOKEN: ""
