apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: bookmyshow
type: Opaque
stringData:
  DB_USERNAME: "bookmyshow_user"
  DB_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  REDIS_PASSWORD: ""
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  TWILIO_ACCOUNT_SID: ""
  TWILIO_AUTH_TOKEN: ""
