global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["api-gateway:8080"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "api-gateway"

  - job_name: "movie-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["movie-service:8082"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "movie-service"

  - job_name: "booking-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["booking-service:8083"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "booking-service"

  - job_name: "notification-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["notification-service:8085"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "notification-service"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
